### ISSUE TITLE
Suggestion: Use pytest and tox

### ISSUE THREAD

**Issue by vitorbaptista** [okfn-brasil/diario-oficial#109]
I'd like to suggest using [pytest](https://pytest.org) instead of unittest. It's a very small change, the current tests don't need to change at all, and for it we'd get a few nice features from pytest. The one I'm missing the most are more useful assert error messages. For example, if I do `assert my_dict == other_dict` with unittest and it fails, I just get `AssertionError` thrown, without any message. If I use the same code with pytest I get a helpful message saying which elements of the dicts aren't the same. The same for comparing arrays, dicts, or any other element types.

And tox is useful to allow the tests to run using a single command, instead of having to remember `python -m unittest discover` when I want to run the tests outside of Docker. It keeps the virtualenvs configured, sets whatever env variables are necessary, and can also run lint.

These 2 libraries became the standard for most Python projects I see, and for good reason: they're great!

I'd be happy to send a PR with these changes (or just pytest) if you agree.

cc @irio @cuducos

**Comment by cuducos** [comment]
Just to clarify: I do like `pytest` and have nothing against bringing it in. My doubt is about `tox`: if we have `pytest` we can run tests with `$ pytest`, so there's no `$ python -m unittest discover`. This checks out the _run using a single command_, right? Thus can you clarify what you mean by _it keeps the virtualenvs configured, sets whatever env variables are necessary, and can also run lint_?

I mean… virtualenv and envvars should be configured in order to run the project, so I'm not sure about your point about _fixing_ that using `tox`… I'm afraid that encapsulating it for tests can pass the wrong impression that the dev environment is OK when it's not.

**Comment by vitorbaptista** [comment]
@cuducos `tox` is useful because we have multiple test types: unit, integration and linting. Personally, I like `tox` to run all the tests (including linting), and allow things like `tox -e unit`, `tox -e integration` and `tox -e lint` for when you want to run each one separately.

The virtualenv and envvars should be configured in order to run the project, but the env vars for test and for development can (and usually are) different, for example `NODE_ENV=development` vs `NODE_ENV=test`, switching the test and development databases being used, etc. Same for keeping the test and development dependencies separated.

**Comment by cuducos** [comment]
> @cuducos `tox` is useful because we have multiple test types: unit, integration and linting. 

Right now we don't have unit tests separated from integration tests, and linting is in a pre-commit Git hook.

>  the env vars for test and for development can (and usually are) different

I can't see a use case for that in this project. Would you mind expanding on it?

I raised this two issues because bringing `tox` in sounds like premature optimization in this particular case.

**Comment by cuducos** [comment]
> so tox would only be useful to run the tests and scrapy check.

Fair enough : ) Let's go with `pytest` and `tox` then!

**Comment by vitorbaptista** [comment]
Fixed by #111. We didn't add `tox` yet, there is an explanation on why in that PR.
