### ISSUE TITLE
Replacement for Scrapy Contracts

### ISSUE THREAD

**Issue by Irio** [okfn-brasil/diario-oficial#44]
@rennerocha recently [raised the issue](https://github.com/okfn-brasil/diario-oficial/pull/43#issuecomment-390254091) of Scrapy Contracts often making the test suite fail due to false positives.

The initial idea of using Contracts was to have a quick (for experienced developers) and beginner-friendly way of writing Scrapy tests, exempting developers from having to write test cases, creating fixtures and maintaining them up-to-date.

We could also keep using Contracts, knowing they will eventually fail in online tests, using them only as a way of monitoring the state of all crawlers (today we have 13 different spiders) until we have a better and more robust one.

**Comment by cuducos** [comment]
I think that tests that depend on external resources (an external URL, the DOM of an external webpage etc.) is always troublesome when we try to make it part of our CI. The suite will eventually fail because of something nothing related to our code. However, this is gold IMHO:

> The initial idea of using Contracts was to have a quick (for experienced developers) and beginner-friendly way of writing Scrapy tests, exempting developers from having to write test cases, creating fixtures and maintaining them up-to-date.

I think we could be less pragmatic about Scrapy Contracts: we know they will fail. We could use them not as part of the CI, but as part of an sort of _integration monitor_ outside the CI.

This will avoid raising red flags in PRs (that might not be friendly for beginners), and make the PR/review/merge process more seamless. But we keep it running elsewhere and it will let us know when some Spider needs to be updated, or even tell us stories about cities publishing gazettes in months that are way past behind…

**Comment by rennerocha** [comment]
I have some discussions at the company on better ways to test spiders. One thing that we mostly agreed is that it is better to monitor the spider execution than try to unit test its code, as the pages changes and the content is not always reliable. We even have a tool (unfortunately not open-sourced yet) that we can include monitoring (checking the existence of errors, the structure of the data returned, etc). It is not ideal so if someone else have better ideas it will be great to hear!

One thing that could be tested are utilitarian code (like pipelines, processors, simple functions) that we use and it is not related to the content of the pages we are scraping. We could think about custom contracts (https://doc.scrapy.org/en/latest/topics/contracts.html#custom-contracts) to create better ways to validate if the spider is working well, but I have never used it.

But I agree with @cuducos that it'd be better if contracts failures didn't break the build, so we won't have a lot of red flags in the PRs.

**Comment by Irio** [comment]
Just changed the CI to run only unit tests, leaving the contracts for when running in the local environments.

Once we have automation on the data collection tasks, a monitoring system may be configured and the contracts removed.
